name: Playwright API tests
on:
  workflow_dispatch:

env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_NAME: ${{ vars.USER_NAME }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test --project=conduit
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
